apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-scraper
  namespace: ai-research-platform
  labels:
    app: data-scraper
    component: data-collection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-scraper
  template:
    metadata:
      labels:
        app: data-scraper
        component: data-collection
    spec:
      containers:
      - name: data-scraper
        image: ai-research-platform/data-scraper:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: PYTHON_ENV
          value: "production"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-scraper
  namespace: ai-research-platform
  labels:
    app: data-scraper
    component: data-collection
spec:
  selector:
    app: data-scraper
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
