apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-transformer
  namespace: ai-research-platform
  labels:
    app: data-transformer
    component: data-processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-transformer
  template:
    metadata:
      labels:
        app: data-transformer
        component: data-processing
    spec:
      containers:
      - name: data-transformer
        image: ai-research-platform/data-transformer:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: PYTHON_ENV
          value: "production"
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-transformer
  namespace: ai-research-platform
  labels:
    app: data-transformer
    component: data-processing
spec:
  selector:
    app: data-transformer
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
