apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-research-platform

resources:
  # Namespace
  - namespace.yaml
  
  # Data Collection
  - data-collection/data-crawler-deployment.yaml
  - data-collection/data-scraper-deployment.yaml
  
  # Data Processing
  - data-processing/data-preprocessor-deployment.yaml
  - data-processing/data-transformer-deployment.yaml
  
  # Data Storage
  - data-storage/mongodb-statefulset.yaml
  - data-storage/postgres-statefulset.yaml
  - data-storage/minio-statefulset.yaml
  
  # ML Framework
  - ml-framework/ml-trainer-deployment.yaml
  - ml-framework/ml-evaluator-deployment.yaml
  
  # API Gateway
  - api-gateway/api-gateway-deployment.yaml
  
  # Frontend Applications
  - research-dashboard/research-dashboard-backend-deployment.yaml
  - research-dashboard/research-dashboard-deployment.yaml
  - web-generator/web-generator-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-research-platform
